# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /asalazar516/
title: Adrian Salazar
author: Adrian Salazar
description: Personal blog and resume
avatar: profile.jpg
email: asalazar51694@gmail.com
github: asalazar516 # username
# twitter: username
linkedin: asalazar516
itchio: one-person
# stackoverflow: username   #e.g: users/2735833/proton1h1
# medium: username #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1
resume: Resume_Adrian_Salazar.pdf


# needed for travis-ci build
exclude: [vendor]
